### ISSUE TITLE
Hi I think the recording api call is missing in doc

### ISSUE THREAD

**Issue by incomingflyingbrick** [VideoExpertsGroup/Chrome-RTSP-Player#1]
Hi i was reading API.md and i couldn't find the js example of recording to MP4, could you add that to the doc please? or could you show a example in the issue ?
Thanks alot it's a great library

**Comment by bleikher** [comment]
Hi,
Record example located here:
http://rtpstream.com/nacl_player_stor/

Use StartRecord/StopRecord buttons to start/stop streaming record.
Please note, that vxgplayer.zip libraries are different and basic one from https://www.videoexpertsgroup.com/nacl_player_api/ 
hasn't record functions.

Best Regards,
Alexey
