### ISSUE TITLE
NaCL build

### ISSUE THREAD

**Issue by berlincount** [VideoExpertsGroup/Chrome-RTSP-Player#12]
Hello,

thanks for this software :) is there any way to get a NaCL version of it? I'm trying to use https://github.com/MichMich/MagicMirror which uses https://github.com/electron/electron which doesn't support PNaCL per https://github.com/electron/electron/issues/3300 ...

I'm trying to get the background picture to be a live stream from an IP camera using RTSP ...

Cheers,

  count

**Comment by bleikher** [comment]
Hello,

Yes,
NaCl version could be installed from the chrome store
https://chrome.google.com/webstore/detail/vxg-media-player/hncknjnnbahamgpjoafdebabmoamcnni

You can launch it directly in chrome via 
chrome://apps
VXG Media Player

Thanks,
Alexey Bleikher
Solution Architect | VXG
www.videoexpertsgroup.com

**Comment by berlincount** [comment]
Hm. Does that help for electron on a Raspberry Pi 3? I'll try, but ...

**Comment by berlincount** [comment]
Okay, that definitely doesn't work, the `CRX` only contains `_platform_specific/x86-64/media_playern_x86_64.nexe`, meaning it will not work on Raspberry Pi 3.

Can you provide build instructions for the NaCL version, or maybe just add a build target?

Thanks in advance!

**Comment by bleikher** [comment]
Hello Berlincount,

Could you please describe in detail your requirements and send them to support@videoexpertsgroup.com ?

Thanks a lot,
Alexey Bleikher
Solution Architect | VXG
www.videoexpertsgroup.com

**Comment by berlincount** [comment]
Of course. For transparency towards the OpenSource community, I'll also post a copy here.

Given the following setup:
- Wall-mounted flatscreen TV
- Raspberry Pi 3 connected via HDMI
- [HI3518EV-based](http://www.hkvstar.com/product-news/2mp-1080p-ip-camera-solution-hi3518ev200-sc2135.html) IPTV camera (outputs FullHD H264 stream via RTSP)

I want to:
- Use [MagicMirror](https://magicmirror.builders/) to display an OSD
- Instead of acting as a mirror, the backdrop should be the video from the camera

My current problem: MagicMirror uses [Electron](https://github.com/electron/electron), a Chromium-based HTML5-Application runner, which does not and will never support PNaCl.

As there is no precompiled NaCl version for Raspberry Pi 3 (that I could find) I'd need to build the Chrome-RTSP-Player for integration into Electron myself, for which the current set of build scripts don't offer an option that I could see.

My support request: please provide a NaCl version of the Player for Raspberry Bi as well as publish the build scripts used to created NaCl versions for any platform alongside the other code :)

Many thanks in advance!

**Comment by a1209492** [comment]
Hello Everyone!

is there any NaCI version of the VXG Player for Raspberry Pi?

Regards,
Umair

**Comment by bleikher** [comment]
Hi Umair,

We don't plan make the build of VXG Media Player NaCl in ARM architecture,
since we don't sure that Google will keep support of chrome apps for non-google OS.
Now VXG Media Player NaCl chrome app was built for x86/64 arhitecture only.

Alexey Bleikher
Solution Architect | VXG
www.videoexpertsgroup.com
