### ISSUE TITLE
Latency issue

### ISSUE THREAD

**Issue by imraansarwar** [VideoExpertsGroup/Chrome-RTSP-Player#17]
Hi, thanks a lot for this useful plugin.
I have set the latency to 200ms as I need to stream near real time. The player initially follows 200ms however the latency keeps on increasing with time and goes beyond a minute, making it not fit for purpose. Can you please suggest what can be done to strictly keep the latency in control.
Environment: Windows 10
I have tested the same stream running for hours in VLC application (native) with 200 ms and it works fine as expected.
>> I can see lot of Errors in chrome console: player ERROR: 7 decoder:0
Warm Regards,
Imran

**Comment by bleikher** [comment]
Hi,
to decrease latency please turn off A/V sync too.
You could test A/V sync off on the page https://www.videoexpertsgroup.com/nacl_player_api/.

ERROR:7 is the same as
MEDIA_ERR_BANDWIDTH = 7,
it means that the latency exceeded threshold and could not be avoided automatically.

Thanks,
Alexey Bleikher
Solution Architect | VXG
www.videoexpertsgroup.com
