### ISSUE TITLE
Multicast UDP stream not working.

### ISSUE THREAD

**Issue by nadbadg** [VideoExpertsGroup/Chrome-RTSP-Player#18]
I have a streaming application that multicast UDP stream  on a Group IP : 224.0.0.1 and port 5000 . i have tested with Unicast UDP stream with my local machine IP it works fine . But when  i run in the player with the multicast IP it shows "Problem with network". I have also set the "connection_udp: 1".  Thanks in advance .

**Comment by bleikher** [comment]
Hi,

Unfortunately, multicast UDP is not supported by Chrome' nacl_io library, there are several related to multicast setsockopt() parameters that Google did not include.
So, TCP and unicast UDP work in VXG Media Player chrome plugin.

Thanks,
Alexey Bleikher
Solution Architect | VXG
www.videoexpertsgroup.com
