### ISSUE TITLE
local or share video

### ISSUE THREAD

**Issue by esmonica** [VideoExpertsGroup/Chrome-RTSP-Player#2]
Hi,
Would it be possible to:
Grab a video frame? Play it frame by frame? 
Get video current time? ie. how many seconds are we in?
Increase/Decrease playback speed?
Thanks

**Comment by bleikher** [comment]
Hi,

Please look at latest player
http://rtpstream.com/nacl_player_api/

1. pause implemented
2. capture frame in jpeg implemented.

Mostly player was intended for live/RTSP playback,
local playback functions weren't implemented yet ( set position, change speed etc).

Thanks,
Alexey Bleikher
bleikher@videoexpertsgroup.com
