### ISSUE TITLE
Why I cannot connect to vxg media player server when I write off this line of code

### ISSUE THREAD

**Issue by Devillo** [VideoExpertsGroup/Chrome-RTSP-Player#22]
"window.location.href = "http://www.videoexpertsgroup.com/player_start/";"
this code in line 60.
when i write off this code. i cannot connet to  vxg media player server.
the error is cannot connet to "127.0.0.1:8778".

**Comment by bleikher** [comment]
Hi Devillo,
Yes, this line starts 'VXG Media Player' chrome app.
You can ensure by launch chrome task manager (SHIFT+ESC).
Please don't remove it from the script.

Regards,
Alexey Bleikher
Solution Architect | VXG
www.videoexpertsgroup.com

**Comment by Devillo** [comment]
Hi bleikher,
If i cannot connect to the out net .How can I start the 'VXG Media Player' chrome app.

**Comment by bleikher** [comment]
Hi,

The url "http://www.videoexpertsgroup.com/player_start/";"
is just trick for start installed chrome app "VXG Media Player", you could find it in chrome://apps or chrome://extensions. The app once installed from chrome store, then the network access not needed for use chrome app "VXG Media Player".
You can type and check that entering "http://www.videoexpertsgroup.com/player_start/" does nothing just lauches "VXG Media Player" process.

Regards,
Alexey Bleikher
Solution Architect | VXG
www.videoexpertsgroup.com

**Comment by Devillo** [comment]
Hi bleikher,
Thanks.I am chinese, in our country, most people can not install "VXG Media Player" from chrome store.So I install it use zip.I thought it would be a problem.Your plugin has solved a lot of problems for me.Finally, thanks for your answer.
