### ISSUE TITLE
Chrome Extension not installing in 32bit system

### ISSUE THREAD

**Issue by Prakashpaarthipan** [VideoExpertsGroup/Chrome-RTSP-Player#25]
The player works well in 64bit Windows PC, But i got error message in 32bit windows pc while installing chrome vxg player extensions. error message is  ( WEBGL  is interrupted)
extension is not installing.

**Comment by contona68** [comment]
Hi,
Your graphics card must support webgl
Software may be supported but hardware (gpu) is not supported
Check the command (chrome: // gpu) at the address and see the result
I hope your problem is resolved
