### ISSUE TITLE
How do I play UDP streams?

### ISSUE THREAD

**Issue by funkytaco** [VideoExpertsGroup/Chrome-RTSP-Player#3]
I have RTMP working. 

How do I play UDP url's like udp://@10.0.0.1:10000 ? Should it work the same way?

**Comment by bleikher** [comment]
Hi,

Please look at 
http://rtpstream.com/nacl_player_api/

set
connection-udp="1" 
and UDP should work as expected.

Thanks,
Alexey Bleikher
