### ISSUE TITLE
TypeError: t.module.command is not a function

### ISSUE THREAD

**Issue by xyy7260** [VideoExpertsGroup/Chrome-RTSP-Player#31]
surroundings：
"react-router"
"react"

steps:
When I play the rtsp video on the A page, I jump to the B page and then jump to the A page to continue playing the video

![image](https://user-images.githubusercontent.com/23183393/55718325-06c3c700-5a2e-11e9-98e5-ff0d14ba9636.png)

I don't know what caused this.

**Comment by sendtion** [comment]
are you ok？

**Comment by xyy7260** [comment]
@sendtion   你好 最后我们没用这个了插件了。
