### ISSUE TITLE
Can't play rtsp streaming from vlc

### ISSUE THREAD

**Issue by Vukia** [VideoExpertsGroup/Chrome-RTSP-Player#4]
I used to play original ip camera rtsp stream and it worked!,
but if I used VLC to generate rtsp relay,
the vlc player can play my relay rtsp stream but VXG sent error message:
Player source error=60930 WSS status=4.
Is VXG chrome plugin didn't recongize  vlc generated rtsp stream?
Thanks for help

**Comment by bleikher** [comment]
It's MEDIA_ERR_SOURCE error,
so, something wrong happens related to media formats.
Please check that you've used MPEG2/MPEG4/H264 video.
Could you please share the link you tried?

Thanks,
Alexey

**Comment by Vukia** [comment]
The ip camera rtsp stream media format is h264,/mlaw,
The vlc generated rtsp stream is the same, without any transcode process.
The ip camera isn't in public internet domain, I'll try to share the rtsp link for you, thankls

**Comment by Vukia** [comment]
Dear Alexey,
If you have a ip camera, you can install vlc and then type this example command: 
vlc rtsp://admin:admin@10.0.10.56/live2.sdp :sout=#rtp{sdp=rtsp://:554/test.sdp} :sout-keep

and test the relay streaming from rtsp://localhost:554/test.sdp.
I'm sorry that I can't get authority to publish my ip camera to internet, I will find other ways to
provide the relay stream, thanks for your help:)

**Comment by bleikher** [comment]
I started relaying with local camera ip,
but actually output stream isn't played neither vlc and ffmpeg
vlc rtsp://localhost:554/test.sdp
ffmpeg -i rtsp://localhost:554/test.sdp

./ffplay -i  rtsp://localhost:554/test.sdp
    nan A-V:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0
ffplay version N-51433-g551f683 Copyright (c) 2003-2013 the FFmpeg developers
  built on Mar 28 2013 21:52:57 with gcc 4.8.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 22.101 / 52. 22.101
  libavcodec     55.  2.100 / 55.  2.100
  libavformat    55.  0.100 / 55.  0.100
  libavdevice    55.  0.100 / 55.  0.100
  libavfilter     3. 48.105 /  3. 48.105
  libswscale      2.  2.100 /  2.  2.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  2.100 / 52.  2.100
[rtsp @ 041fb060] UDP timeout, retrying with TCP
[rtsp @ 041fb060] method PAUSE failed: 405 Client error
[rtsp @ 041fb060] Could not find codec parameters for stream 0 (Video: h264): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[rtsp @ 041fb060] Estimating duration from bitrate, this may be inaccurate
rtsp://localhost:554/test.sdp: could not find codec parameters


Also, if you use UDP, the plugin default setting TCP only.
For using UDP, please set up the attribute connection-udp="1"

Best Regards,
Alexey

**Comment by Vukia** [comment]
Thanks for your help!
Now I got a special case that I can play my relay stream from vlc.
First, set vlc to use tcp for rtp transfer.
Second, set vxg player connection-udp="1",
Now I can play my relay stream!
But if I change the relay muxer to ts, the VXG still can't play my relay stream,
does VXG support ts muxer with rtsp ?

**Comment by bleikher** [comment]
Yes, mpeg2 transport stream container is supported,
for exampe you can check any HLS stream like a
http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8
