### ISSUE TITLE
Use the plugin in react component

### ISSUE THREAD

**Issue by lllbahol** [VideoExpertsGroup/Chrome-RTSP-Player#7]
I want to use the plugin in a react component to play rtsp video. So i export the vxgplayer function from vxgplayer.js and import it in react component, and then run it in the lifecycle componentDidMount, like this

```
componentDidMount() {
  setTimeout(() => {
      const els = document.getElementsByClassName('vxgplayer');
      vxgplayer(els[0].getAttribute('id'), this.defaultOpt);
  }, 1000);
}

```
but it result in Error catch by handleError, and i dont konw why.
I think they might cause the problem but not sure
1. import the js as a module instead of use them in <script>
2. use componentDidMount instead of domContentLoad listener
3.  i run the project in a node server

**Comment by TracyWei** [comment]
I also have the same issue!

**Comment by bleikher** [comment]
Hi,

Please try latest version at
http://rtpstream.com/nacl_player_api/

It includes an angular 2 example,
maybe it helps.

Thanks,
Alexey Bleikher
bleikher@videoexpertsgroup.com

**Comment by birdage** [comment]
@lllbahol @TracyWei you need to make sure the nmf_src and path are reflected in your app, and are accessible in the public directory.

> eg

```
vxgplayer(playerId, {
      url: 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov',
      nmf_path: 'media_player.nmf',
      nmf_src: 'pnacl/Release/media_player.nmf',
```

**Comment by xyy7260** [comment]
@birdage   Hello, I also encountered this problem in react, when I played it.
NativeClient: manifest JSON parsing failed: Line: 1, column: 1, Unexpected token
